DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS cargo;
DROP TABLE IF EXISTS perfil;

DROP SEQUENCE IF EXISTS SQ_CARGO;
DROP SEQUENCE IF EXISTS SQ_USUARIO;
DROP SEQUENCE IF EXISTS SQ_PERFIL;

--CRIACAO DAS TABELAS
CREATE TABLE cargo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(250) NOT NULL
);

CREATE TABLE perfil (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(250) NOT NULL
);

CREATE TABLE usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(250) NOT NULL,
  cpf VARCHAR(11) NOT NULL,
  sexo VARCHAR(1) NOT NULL,
  data_nascimento DATE NOT NULL,
  ativo BOOLEAN NOT NULL,
  fk_cargo INT NOT NULL,
  fk_perfil INT NOT NULL
);

-- Criacao das FKs
ALTER TABLE usuario
    ADD FOREIGN KEY (fk_cargo) 
    REFERENCES cargo(id);

ALTER TABLE usuario
    ADD FOREIGN KEY (fk_perfil) 
    REFERENCES perfil(id);

-- CREATE SEQUENCES

CREATE SEQUENCE SQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_CARGO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_PERFIL START WITH 1 INCREMENT BY 1;

--INSERTS
INSERT INTO cargo(id, nome) VALUES (SQ_CARGO.NEXTVAL, 'Gerente');
INSERT INTO cargo(id, nome) VALUES (SQ_CARGO.NEXTVAL, 'Supervisor');
INSERT INTO cargo(id, nome) VALUES (SQ_CARGO.NEXTVAL, 'Administrativo');

INSERT INTO perfil(id, nome) VALUES (SQ_PERFIL.NEXTVAL, 'Administrador');
INSERT INTO perfil(id, nome) VALUES (SQ_PERFIL.NEXTVAL, 'Comum');